#!/bin/sh
set -eu
cd -- "$(dirname -- "$0")"

rm -rf pack
gh tailor download --outdir pack "codeql/javascript-queries"

mkdir -p pack/tailor
cp SourcesAndSinks.qll pack/tailor/
cp dependencies.ql pack/
cp debug.qls pack/codeql-suites/

gh tailor \
  set-pack-meta \
  --name "ghas-trials/javascript-debug-queries" \
  --version "0.0.0" \
  --default-suite "codeql-suites/debug.qls" \
  pack

find pack/Security/ -name '*.ql' -type f | while read f; do
  if [ "$f" = "pack/Security/CWE-020/IncompleteUrlSubstringSanitization.ql" ]; then
    continue
  fi
  perl -i -0777 -p -e 's/^\s*(from\s+.*?\s+(where\s+.*?\s+)?)?select\s+.*//ms' "$f"
  perl -i -0777 -p -e 's/^\s*query\s+predicate\s+(problems|nodes|edges)\b.*//ms' "$f"
  perl -i -0777 -p -e 's/^import (DataFlow::)?PathGraph$//ms' "$f"
  gh tailor ql-import -m "tailor.SourcesAndSinks" "$f"
  id="$(gh codeql \
          resolve metadata \
          --format json \
          "$f" \
          | jq -r '.id')"
  id="${id}-debug"
  gh tailor \
    set-ql-meta \
    -m "kind" "diagnostic" \
    -m "id" "$id" \
    -d "security-severity" \
    -d "problem.severity" \
    -d "precision" \
    "$f"
done

gh tailor create -i pack
