#!/bin/sh
set -eu

mkdir -p stage/tailor
cp SourcesAndSinks.qll stage/tailor/
cp dependencies.ql stage/
cp debug.qls stage/codeql-suites/

gh tailor \
  set-pack-meta \
  --name "ghas-trials/javascript-debug-queries" \
  --version "0.0.0" \
  --default-suite "codeql-suites/debug.qls" \
  stage

find stage/Security/ -name '*.ql' -type f | while read f; do
  if [ "$f" = "stage/Security/CWE-020/IncompleteUrlSubstringSanitization.ql" ]; then
    continue
  fi
  perl -i -0777 -p -e 's/^\s*(from\s+.*?\s+(where\s+.*?\s+)?)?select\s+.*//ms' "$f"
  perl -i -0777 -p -e 's/^\s*query\s+predicate\s+(problems|nodes|edges)\b.*//ms' "$f"
  perl -i -0777 -p -e 's/^import (DataFlow::)?PathGraph$//ms' "$f"
  gh tailor ql-import --module "tailor.SourcesAndSinks" --visible "$f"
  id="$( \
    gh codeql \
    resolve metadata \
    --format json \
    "$f" \
    | jq -r '.id' \
  )"
  gh tailor \
    set-ql-meta \
    -m "kind" "diagnostic" \
    -m "id" "${id}-debug" \
    -d "security-severity" \
    -d "problem.severity" \
    -d "precision" \
    "$f"
done
