#!/bin/sh
set -eu
cd -- "$(dirname -- "$0")"

db="integration_test_db"
results="integration_test_results.csv"
rm -rf "$db" "$results"

gh tailor \
  make-min-db \
  --language "javascript" \
  "$db"

gh codeql \
  database analyze \
  --threads 0 \
  --additional-packs pack \
  --format csv \
  -vvv \
  --output "$results" \
  "$db" \
  "ghas-trials/javascript-debug-queries"
