#!/bin/sh
set -eu
cd -- "$(dirname -- "$0")"

rm -rf pack

gh tailor download --outdir pack "codeql/python-queries"

gh tailor \
  set-pack-meta \
  --name "zbazztian/origin-python-queries" \
  --version "0.0.0" \
  --default-suite "codeql-suites/python-code-scanning.qls" \
  pack

mkdir pack/tailor
cp OriginCustomizations.qll pack/tailor/

find 'pack/Security' -name '*.ql' -print0 | xargs -0 gh tailor ql-import -m "tailor.OriginCustomizations"

gh tailor create -i pack
