name: "Pull Request Checks"

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    name: Build and Test CodeQL Packs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Test
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         gh extensions install github/gh-codeql
         gh extensions install zbazztian/gh-tailor
         gh codeql set-version "v$(gh tailor actions-cli-version)"
         ./test "${{ matrix.language }}"
